### ISSUE TITLE
Question about the Baseline results in your paper

### ISSUE THREAD

**Issue by Z-Zheng** [DIUx-xView/xView2_baseline#14]
I wonder which split the Baseline results (Table. 3) were computed on,  in xBD paper (https://arxiv.org/abs/1911.09296).
test or hold?

Thanks.

**Comment by RitwikGupta** [comment]
@Z-Zheng They were computed on the test set!

**Comment by Michaeljurado42** [comment]
So the process to obtain the benchmark in table 3 is to 1) run process_data.py on the test set and then 2) Classify each (128, 18, 3) patch produced and tabulate the results?

**Comment by RitwikGupta** [comment]
@Michaeljurado24 That's correct. Or run the Docker containers for each of the top five models via their runfiles.

**Comment by Michaeljurado42** [comment]
@RitwikGupta Thank you for your rapid response yesterday. I have tried to replicate the results of the paper today using the linked [weights](https://github.com/DIUx-xView/xView2_baseline/releases/tag/v1.0) in the repository and have run into trouble. Namely when I run: 
`python model/damage_inference.py --test_data .../xBD_output --test_csv .../test.csv --model_weights .../classification.hdf5 --output_json .`

I see this error
`Traceback (most recent call last):
  File "model/damage_inference.py", line 161, in <module>
    main()
  File "model/damage_inference.py", line 157, in main
    run_inference(args.test_data, args.test_csv, args.model_weights, args.output_json)
  File "model/damage_inference.py", line 94, in run_inference
    model.load_weights(model_weights)
  File "/home/mjurado3/.conda/envs/baseline-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/home/mjurado3/.conda/envs/baseline-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1266, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/mjurado3/.conda/envs/baseline-gpu/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 707, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/mjurado3/.conda/envs/baseline-gpu/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3384, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/home/mjurado3/.conda/envs/baseline-gpu/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 846, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/mjurado3/.conda/envs/baseline-gpu/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1117, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 1, 256, 512) and (512, 128, 1, 1) are incompatible`

This kind of error suggests to me that the architecture changed since the weights were last generated.

**Comment by Michaeljurado42** [comment]
Nevermind, I am pretty sure that downgrading to tensorflow 1.15 fixed the problem.

**Comment by successhaha** [comment]
Hello, where did you get the label in the test dataset? The test data set I downloaded has no labels.

**Comment by RitwikGupta** [comment]
@successhaha The xView2 website has all labels available for download as a separate link.
